### ISSUE TITLE
Running CI from a fork doesn't work

### ISSUE THREAD

**Issue by ntBre** [openforcefield/yammbs-dataset-submission#29]
See #28. The optimization benchmark failed with

```
Traceback (most recent call last):
  File "/home/ubuntu/_work/yammbs-dataset-submission/yammbs-dataset-submission/main.py", line 62, in <module>
    conf = Config.from_file(sys.argv[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/_work/yammbs-dataset-submission/yammbs-dataset-submission/config.py", line 13, in from_file
    with open(filename) as inp:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'submissions/2024-12-19-Sage-2.2.1-lipids-aux/input.yaml'
```

In other words, it can't find the YAML file input file, despite my having copied the file path from the GitHub UI (I also pulled the branch locally and `ls submissions/2024-12-19-Sage-2.2.1-lipids-aux/input.yaml` runs just fine from the root of the repo).

Under the checkout action, the hash being printed is `'7e22ab606b080e9696411140797fa76a06abd966'`, which corresponds to the master branch (the last torsion benchmark run correctly prints `'d184dcf4574c04a0f08cf50131ad37b1c1d224cd'`, which is the penultimate commit in the torsion branch). My hypothesis is that the fork is confusing the checkout process, which can possibly be fixed based on this comment: https://github.com/actions/checkout/issues/455#issuecomment-792228083, which suggests adding these options to the checkout action:

``` yaml
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
```

I was going to try making this modification directly on @JHoeflich1's branch, but I needed push permissions in the fork. As the linked comment indicates, even if the checkout action pulls the right code with this modification, I think we'll run into the same issue with trying to commit back to the fork.

In short, the current workflow may just not work for forks, which is a little unfortunate. But I wanted to flag it for further investigation after the holidays.
